name = "subconverter-rs"
compatibility_date = "2024-01-01"
pages_build_output_dir = "www/.next"

[env.production.vars]
NODE_ENV = "production"
DEPLOY_ENV = "cloudflare"
WASM_DEBUG = "false"

[env.preview.vars]
NODE_ENV = "development"
DEPLOY_ENV = "cloudflare"
WASM_DEBUG = "true"

compatibility_flags = ["nodejs_compat"]
